// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5zS4PCvbBYmVf8R-PZn81HbecRb6XbAY',
    appId: '1:418913638245:web:623c6dcae1e82ed7cef38c',
    messagingSenderId: '418913638245',
    projectId: 'abu-3meer',
    authDomain: 'abu-3meer.firebaseapp.com',
    storageBucket: 'abu-3meer.firebasestorage.app',
    measurementId: 'G-G9Z3KCG2PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeioMEGMeX3ZVDshOFwjpqIDJarXX5jUo',
    appId: '1:418913638245:android:00026cebabc5a993cef38c',
    messagingSenderId: '418913638245',
    projectId: 'abu-3meer',
    storageBucket: 'abu-3meer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADJTxDTHx-kWjIZp2rD-OaJUGFIl6adyI',
    appId: '1:418913638245:ios:0ebbee61083eab4ccef38c',
    messagingSenderId: '418913638245',
    projectId: 'abu-3meer',
    storageBucket: 'abu-3meer.firebasestorage.app',
    iosClientId: '418913638245-bqtj470v5kk7oig35l2s3ljqj9881h56.apps.googleusercontent.com',
    iosBundleId: 'com.fanleague.fanLeague',
  );
}
