// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5zS4PCvbBYmVf8R-PZn81HbecRb6XbAY',
    appId: '1:418913638245:web:623c6dcae1e82ed7cef38c',
    messagingSenderId: '418913638245',
    projectId: 'abu-3meer',
    authDomain: 'abu-3meer.firebaseapp.com',
    storageBucket: 'abu-3meer.firebasestorage.app',
    measurementId: 'G-G9Z3KCG2PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Q7rvmvMmsJ6i827r_vnY_nUhqhGN29E',
    appId: '1:701810344443:android:4d78f9446bc398a25a4b5e',
    messagingSenderId: '701810344443',
    projectId: 'abu-3meer-9fd70',
    storageBucket: 'abu-3meer-9fd70.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN6OBPnm4wqgAcILPqWGG8jYFLZHq63G4',
    appId: '1:701810344443:ios:d6a1af8e1afb3d725a4b5e',
    messagingSenderId: '701810344443',
    projectId: 'abu-3meer-9fd70',
    storageBucket: 'abu-3meer-9fd70.firebasestorage.app',
    iosBundleId: 'com.abu3meer.app',
  );
}
