#!/bin/sh

set -eu

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 https://your-api-host.example/api/v1" >&2
  exit 64
fi

api_endpoint=${1%/}
if ! printf '%s' "$api_endpoint" | grep -Eq '^https://[A-Za-z0-9.-]+(:[0-9]+)?(/[^[:space:]]*)?$'; then
  echo "API endpoint must be a complete HTTPS URL without spaces." >&2
  exit 64
fi

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
project_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
ios_config="$project_dir/ios/Flutter/ApiEndpoint.local.xcconfig"
flutter_config="$script_dir/api_endpoint.local.json"
dart_define=$(printf 'API_BASE_URL=%s' "$api_endpoint" | base64 | tr -d '\n')

umask 077
{
  printf '// Generated by tool/configure_api_endpoint.sh; intentionally git-ignored.\n'
  printf 'DART_DEFINES = $(inherited),%s\n' "$dart_define"
} > "$ios_config"

{
  printf '{\n'
  printf '  "API_BASE_URL": "%s"\n' "$api_endpoint"
  printf '}\n'
} > "$flutter_config"

echo "Configured API_BASE_URL=$api_endpoint"
echo "Xcode will use it when Runner.xcworkspace is built directly."
echo "Flutter builds can use: --dart-define-from-file=$flutter_config"
