default_platform(:ios)

platform :ios do
  lane :check_testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("APP_STORE_CONNECT_KEY_ID"),
      issuer_id: ENV.fetch("APP_STORE_CONNECT_ISSUER_ID"),
      key_filepath: ENV.fetch("APP_STORE_CONNECT_API_KEY_PATH"),
      in_house: false
    )

    app = Spaceship::ConnectAPI::App.find("com.abu3meer.app")
    builds = app.get_builds
    builds.each do |b|
      UI.success("TestFlight Build #{b.version} -> Processing State: #{b.processing_state} | Upload Date: #{b.uploaded_date}")
    end
  end
end
