import type { CreateNotificationCampaignInput } from './notificationService.js';

export interface ExclusiveVideoNotificationInput {
  videoId: string;
  youtubeId: string;
  title: string;
  thumbnailUrl: string;
  publishedAt: Date;
  memberOnly: boolean;
  createdBy: string;
}

/** Creates the durable campaign generated by the first publication only. */
export function exclusiveVideoNotificationCampaign(
  input: ExclusiveVideoNotificationInput
): CreateNotificationCampaignInput {
  return {
    // Keep the automatic heading language-neutral; the published video title
    // supplies the creator's Arabic or English copy.
    title: 'Abu 3meer',
    body: input.title,
    category: 'challenge',
    // Exclusive-video alerts follow the existing "New challenges" opt-in.
    // Gold-only videos are never announced to non-members.
    targetAudience: input.memberOnly ? 'members_only' : 'all',
    imageUrl: input.thumbnailUrl.startsWith('https://')
      ? input.thumbnailUrl
      : null,
    scheduledFor: input.publishedAt,
    createdBy: input.createdBy,
    sourceType: 'exclusive_video',
    sourceId: input.videoId,
    data: {
      route: '/exclusive',
      videoId: input.videoId,
      youtubeId: input.youtubeId,
    },
  };
}
